### ISSUE TITLE
/file fails hard, if it receives a directory by accident

### ISSUE THREAD

**Issue by tmaier** [jiggy-ai/pair#7]
I have a file called `config.ru``config/config.rb` and when typing this, I might end up pressing `<ENTER>` while I haven't finished typing. This means `/file config` would be executed. 

This leads to an exception and pair exits right away

```
/file config
Traceback (most recent call last):
  File "/usr/local/bin/pair", line 8, in <module>
    sys.exit(repl())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pair_ai/pair.py", line 64, in repl
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'config'
```

**Comment by amy-why** [comment]
0.5.6 fix this. Thanks!
