### ISSUE TITLE
ChatContext got unexpected argument

### ISSUE THREAD

**Issue by daviddavini** [jiggy-ai/pair#9]
This looks really awesome! However, it's not working for me. 
After a fresh install with `pip install pair_ai`, I get this error:

```zsh
$ pair                                    
Traceback (most recent call last):
  File "/Users/daviddavini/Code/patchgpt/venv/bin/pair", line 5, in <module>
    from pair_ai.pair import repl
  File "/Users/daviddavini/Code/patchgpt/venv/lib/python3.11/site-packages/pair_ai/pair.py", line 29, in <module>
    chat_ctx = ChatContext(min_response_tokens=800,  # leave room for at least this much
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ChatContext.__init__() got an unexpected keyword argument 'max_context_assistant_messages'
```

**Comment by wskish** [comment]
sorry about that. there was some recent change to the chatstack depdency which didn't seem to propagate here.  I need to track that down

**Comment by mikethm** [comment]
works with the latest commit. 
clone into a local directory and 
run 
```
pip install .
```

**Comment by daviddavini** [comment]
That's what I ended up doing, it works great! Thanks
